spring:
  application:
    name: itoken-zipkin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9411

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
