spring:
  application:
    name: itoken-web-admin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9763

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/